title: Your awesome title
author: Geraldo Rebouças
email: gfs.reboucas@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Brazilian Mechanical Engineer.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
